substitutions:
  devicename: livingroom_blinds
  upper_devicename: Livingroom Blinds
  # Do not use single password for all API's, this is just for sample
  masterpassword: "yourpasswordhere"
  
esphome:
  name: $devicename
  platform: ESP8266
  board: esp12e
  includes:
    - am43.h

# Enable logging
#logger:
#  baud_rate: 0

# Enable Home Assistant API
api:
  password: $masterpassword

ota:
  password: $masterpassword

wifi:
  ssid: "yourssidhere"
  password: $masterpassword
  
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AM43 Blinds"
    password: $masterpassword

captive_portal:

status_led:
  pin: 2

# UART connected to AM43 MCU
uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 19200

cover:
  - platform: custom
    lambda: |-
      auto cover = new AM43Component(id(uart_bus));
      App.register_component(cover);
      return {cover};

    covers:
      - name: ${upper_devicename} Cover
        id: am43_cover

# Additional battery and light level sensors
sensor:
- platform: custom
  lambda: |-
    auto cover = (AM43Component*)id(am43_cover);
    return {cover->m_sensor_battery, cover->m_sensor_light};
  sensors:
    - name: ${upper_devicename} Battery
    - name: ${upper_devicename} Light Level